### ISSUE TITLE
problem about nerfstudio training

### ISSUE THREAD

**Issue by MouseChannel** [kerrj/lerf#53]
outputs\ramen\dino.info
Traceback (most recent call last):
  File "D:\MoCheng\lerf\lerf\data\utils\feature_dataloader.py", line 55, in try_load
    self.load()
  File "D:\MoCheng\lerf\lerf\data\utils\feature_dataloader.py", line 38, in load
    raise FileNotFoundError
FileNotFoundError

and  the last line is

urllib.error.HTTPError: HTTP Error 403: rate limit exceeded

**Comment by MouseChannel** [comment]
is that means not exist  `outputs\ramen\dino.info` file?

**Comment by PrinceWYS** [comment]
I met the same problem. Have you solved it? Thanks!
